### ISSUE TITLE
possible issues upgrading on ubuntu - fyi

### ISSUE THREAD

**Issue by Aranjedeath** [EggieCode/wireguard-ppa#16] opened 2017-04-18 17:49 UTC
```
jacob@kafka:~$ sudo apt install wireguard-tools     
[sudo] password for jacob: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following package was automatically installed and is no longer required:
  libqt5keychain1
Use 'sudo apt autoremove' to remove it.
The following additional packages will be installed:
  openresolv
The following packages will be REMOVED:
  resolvconf
The following NEW packages will be installed:
  openresolv
The following packages will be upgraded:
  wireguard-tools
1 upgraded, 1 newly installed, 1 to remove and 0 not upgraded.
Need to get 68.5 kB of archives.
After this operation, 92.2 kB disk space will be freed.
Do you want to continue? [Y/n] y
Get:1 https://mirrors.ocf.berkeley.edu/ubuntu xenial/universe amd64 openresolv amd64 3.7.2-1 [21.2 kB]
Get:2 http://ppa.launchpad.net/wireguard/wireguard/ubuntu xenial/main amd64 wireguard-tools amd64 0.0.20170409-wg2~xenial [47.3 kB]
Fetched 68.5 kB in 0s (90.4 kB/s)                                      
dpkg: resolvconf: dependency problems, but removing anyway as you requested:
 ubuntu-minimal depends on resolvconf.

(Reading database ... 370565 files and directories currently installed.)
Removing resolvconf (1.78ubuntu4) ...
resolvconf.postrm: Reboot recommended
Processing triggers for man-db (2.7.5-1) ...
Selecting previously unselected package openresolv.
(Reading database ... 370550 files and directories currently installed.)
Preparing to unpack .../openresolv_3.7.2-1_amd64.deb ...
Unpacking openresolv (3.7.2-1) ...
Preparing to unpack .../wireguard-tools_0.0.20170409-wg2~xenial_amd64.deb ...
Unpacking wireguard-tools (0.0.20170409-wg2~xenial) over (0.0.20170324-wg1~xenial) ...
Processing triggers for man-db (2.7.5-1) ...
Setting up openresolv (3.7.2-1) ...
Installing new version of config file /etc/dhcp/dhclient-enter-hooks.d/resolvconf ...
Installing new version of config file /etc/network/if-down.d/resolvconf ...
Installing new version of config file /etc/network/if-up.d/000resolvconf ...
Installing new version of config file /etc/ppp/ip-down.d/000resolvconf ...
Installing new version of config file /etc/ppp/ip-up.d/000resolvconf ...
Setting up wireguard-tools (0.0.20170409-wg2~xenial) ...
jacob@kafka:~$ 
```

main thing to note: this dependency on openresolv breaks ubuntu-minimal (this is apparently not a problem on debian, as debian does not have such depends), which may have implications in the future. Probably the dependency on openresolv should be made elsewhere in ubuntu.

**Comment by EggieCode** [comment] 2017-04-18 19:59
The main for it that resolvconf is broken with wg-quick. 
If you add a nameserver with resolvconf on the wg* interface it will not add it to the top of the nameserver list. Because of the /etc/resolvconf/interface-order.

See where the problem exists from: https://github.com/jlund/streisand/issues/557
and bug on launchpad: https://bugs.launchpad.net/ubuntu/+source/resolvconf/+bug/1680811 

When the bug in launchpad is resolved we will remove the dependency.

**Comment by Aranjedeath** [comment] 2017-04-18 20:55
I have just done some testing, and openresolv is not a drop-in solution for this. Period.

To get openresolv to work in the default situation on ubuntu 16.04 (which is, network-manager operating dnsmasq, in a way that functions) it is necessary to edit the /etc/resolvconf.conf file.

There is a commented-by-default line, `#name_servers=127.0.0.1` that must be uncommented and changed to `name_servers=127.0.1.1` or the users will only have bare libc dns, which will use whatever dns their dhcp gives them (probably home router), instead of whatever they have actually set in their various network-manager interfaces.

**Comment by EggieCode** [comment] 2017-04-19 01:09
Got same with my servers that get ips by dhcp with ifupdown.
I disabled openresolv by setting `resolv_conf=/dev/null` in /etc/resolvconf.conf.
@cryptofuture Any idea's? Maybe set streisand to depend on openresolv instate of the wg-tools package? Or maybe update the resolvconf package to the wireguard ppa?

**Comment by cryptofuture** [comment] 2017-04-19 07:38
I have no idea, _any solution sucks, before it fixed in upstream_. I had a feeling that switching to operesolv could broke something. Up for any solution. 
I think @Aranjedeath  could achieve the same result with commenting `#dns=dnsmasq` in `/etc/NetworkManager/NetworkManager.conf`  
 I didn't have any issues from switch to operesolv in tested 16.04.x server with configuration in `/etc/network/interfaces`
As for ubuntu-minimal is not a problem to add it to Conflicts, since its just a meta package anyway.
But this will not fix network-manager.  I vote for hack resolvconf (add it to ppa) and edit dependency to resolvconf, to switch users back to it.

**Comment by cpu** [comment] 2017-04-19 13:54
> Maybe set streisand to depend on openresolv instate of the wg-tools package? 

My understanding is this is a _client-side_ issue on Ubuntu with wg-tools. Streisand doesn't install that component. At best we could add some additional Ubuntu/resolvconf specific instructions in the documentation Streisand generates for Wireguard client setup.

**Comment by EggieCode** [comment] 2017-04-19 14:53
That makes a huge differance. I think good to vote for the update resolvconf package in the ppa.
But make resolvconf a recommended instate of dependency.
Ubuntu installs is the recommended packages automatic with the `apt-get` default configuration. (Excluding automatic configuration providors like Ansible)

**Comment by cryptofuture** [comment] 2017-04-19 15:28
> Ubuntu installs is the recommended packages automatic with the apt-get default configuration.
 
It will switch back to resolvconf only most users, however dependency will switch back all.
For ex.: I always turn off recommends on production servers (more above I use minimalcd instead of server edition)

**Comment by zx2c4** [comment] 2017-04-19 15:45
@Aranjedeath you wrote:

> I have just done some testing, and openresolv is not a drop-in solution for this. Period.

Your debugging log in #wireguard was extremely disorganized, and I have no faith that you've reached that conclusion through rigorous means. You might be right, but you might be wrong. I'd like to test using a fresh VM before jumping to conclusions, as your methodology appears highly questionable.

**Comment by zx2c4** [comment] 2017-04-19 15:48
@cpu you wrote:

> My understanding is this is a client-side issue on Ubuntu with wg-tools. Streisand doesn't install that component. At best we could add some additional Ubuntu/resolvconf specific instructions in the documentation Streisand generates for Wireguard client setup.

Actually Streisand ships wg0-client.conf files for wg-quick which explicitly state the use of resolvconf using openresolv-only switches. If you've got a better command to run for DNS management in there, then please do make that change.

**Comment by cpu** [comment] 2017-04-19 15:55
> Actually Streisand ships wg0-client.conf files for wg-quick which explicitly state the use of resolvconf using openresolv-only switches. 

Those files are part of the client setup documentation I was referring to updating.

>  If you've got a better command to run for DNS management in there, then please do make that change.

I don't, but I'm watching this thread & the discussion. If clear advice for Ubuntu users arrives I can update the docs & wg0-client config files.

**Comment by Aranjedeath** [comment] 2017-04-19 16:24
If someone other than me could confirm the bug and my fix, that would be great. The approximate steps should be: install a graphic ubuntu install (desktop, I'm not sure this applies to server because I'm not sure they actually use network-manager as extensively), do the ppa-install on the front of this github, say yes to installing openresolv/removing resolveconf, and reboot. Then confirm (through dig?) if you're using the locally installed dnsmasq or not. It's working now, for me, and currently I still get refused responses to queries on 127.0.0.1, and correct ones on 127.0.1.1. Without the fix, the system tries to hit 127.0.0.1, query fails (refused) so it probably falls back to libc resolver or whatever that default is (slow and awful and no caching). With the fix I noted above, the queries are correctly sent to 127.0.1.1 in the default case.

(127.0.1.1 being where dnsmasq is bound by network-manager since quetzal)

**Comment by zx2c4** [comment] 2017-04-19 16:50
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=860564
https://bugs.launchpad.net/ubuntu/+source/resolvconf/+bug/1683884

**Comment by Aranjedeath** [comment] 2017-04-19 17:14
I assume if y'all are going to repackage resolveconf as a shim solution, the change in that bug https://bugs.launchpad.net/ubuntu/+source/resolvconf/+bug/1680811 is probably the one to make until someone can get debian or canonical to deploy openresolv as the standard here.

(I should just say, I'm fully in favor of the problem being fixed where it happens -- upstream. openresolv seems nice.)

**Comment by cryptofuture** [comment] 2017-04-19 17:27
>The approximate steps should be: install a graphic ubuntu install (desktop)
>I assume if y'all are going to repackage resolveconf as a shim solution

@Aranjedeath, I think I gonna test it first, but I need free hour to do it. Will try tomorrow. Its not the problem to add resolvconf to ppa, just we need to make sure, before switching one cripply fix to another.

**Comment by cryptofuture** [comment] 2017-04-20 19:53
@Aranjedeath I can't reproduce (tested on 16.04.2 fresh install in kvm, without updates)  
 What ubuntu version and wireguard configs you used?

**Comment by zx2c4** [comment] 2017-04-21 04:17
I couldn't reproduce either.

**Comment by cryptofuture** [comment] 2017-04-21 08:25
@zx2c4 @EggieCode 
I vote for ignoring changing openresolv (at least for now, or before someone else will get problems with openresolv) with 0.20170421 snapshot. 
Thoughts?
As neutral solution I can package patched resolvconf in own separated ppa.
btw: I can't also open trie_v* pdfs from release notes (in mupdf)

**Comment by EggieCode** [comment] 2017-04-21 09:50
I think that is best idea.

**Closed as completed by EggieCode** 2017-04-21 09:50 UTC

**Comment by Aranjedeath** [comment] 2017-04-21 15:06
The ISO will be done in an hour, after which I'll report here. I use KDE NEON, which is ubuntu 16.04.x with updated KDE libraries and applications.

Yesterday was an unofficial holiday in my state so I didn't work on it.

**Comment by Aranjedeath** [comment] 2017-04-21 16:49
OK. I can tell you what's happening, but not why. I have confirmed that openresolv does not (completely) break dns as in _user has no dns_ but it does wipe out all the benefit of having dnsmasq installed.

With resolvconf, I get zero-ms dns query response times for repeated requests (as expected). With openresolv, all requests are the latency to my nearest DNS, and I cannot even get it to ever cache (0 ms response time).

This is broken. It is (probably) using libc resolver always. Why it will not cache locally... someone with more knowledge in this area needs to chime in. But it isn't, and that's what I can report. 

This was tested on both a fresh and old install of KDE NEON, which at this level is bit-exact copy of Ubuntu 16.04. (the changes are KDE UI libraries, not networking crap)


-- I'll add that I am having weird issues on my laptop because of openresolv, but they are not the same issues as the fresh install, so there's something else happening there. This complete lack of local dns caching is a regression, though. It's probably openresolv's problem and not yours, but still.
